### PR TITLE
Seperates auth/database and rest into two different files

### PR DESCRIPTION
**Pull request by nlumiere**

### CODE REVIEW

**Review by arringtonh — COMMENTED** [review]
lgtm

**Review by aokeke — CHANGES_REQUESTED** [review]
I see a large amount of code being removed from scripts.js and I see chat.js has some stuff, but I don't see where the auth code went. Is there a file missing from this PR?

**Comment by nlumiere** [comment]
> I see a large amount of code being removed from scripts.js and I see chat.js has some stuff, but I don't see where the auth code went. Is there a file missing from this PR?

The auth code is at the beginning, I only copied over the parts of scripts.js which are more recent than chat.js. Check the code of branch 'bugfixing' and it will be there. @aokeke

**Review by aokeke — APPROVED** [review]
LGTM

**Pull request merged**
