### PR TITLE
Allow users to change bio on double click.

### PR DESCRIPTION
**Pull request by arringtonh**

### CODE REVIEW

**Review by leeannachen — COMMENTED** [review]
lgtm; i am assuming that the static bio will get override by the one from the database

**Review by aokeke — COMMENTED** [review]
I don't think I see how this does anything with double clicking. Can you elaborate on how this works?

**Comment by arringtonh** [comment]
there were already existing functions that allowed users to change their bio, it looks like the text field for the bio got deleted though so all I had to do was add it back with the same ID @aokeke

**Review by aokeke — APPROVED** [review]
LGTM

**Pull request merged**
