### PR TITLE
add build file with building and deploying code

### PR DESCRIPTION
**Pull request by aokeke**
Created another cloud build file that will build and deploy the code. I also updated the rules at https://pantheon.corp.google.com/cloud-build/triggers?project=arringtonh-step-2020-d to look for this file when merging to master and to look for the other file when doing any other push.

### CODE REVIEW

**Comment by aokeke** [comment]
Let me know if you think there is a better way to do this or if the file name should be different or something.

**Review by nlumiere — COMMENTED** [review]
If having two steps like this side-by-side works, then great

**Comment by aokeke** [comment]
> If having two steps like this side-by-side works, then great

Tested using `$ cloud-build-local --config=cloudbuildanddeploy.json --dryrun=false --push .`

Which eventually gave
```
Step #1: [INFO] GCLOUD: ...................................done.
Step #1: [INFO] GCLOUD: Deployed service [default] to [https://arringtonh-step-2020-d.uc.r.appspot.com]
Step #1: [INFO] GCLOUD:
Step #1: [INFO] GCLOUD: You can stream logs from the command line by running:
Step #1: [INFO] GCLOUD:   $ gcloud app logs tail -s default
Step #1: [INFO] GCLOUD:
Step #1: [INFO] GCLOUD: To view your application in the web browser run:
Step #1: [INFO] GCLOUD:   $ gcloud app browse --project=arringtonh-step-2020-d
Step #1: [INFO] ------------------------------------------------------------------------
Step #1: [INFO] BUILD SUCCESS
Step #1: [INFO] ------------------------------------------------------------------------
Step #1: [INFO] Total time:  06
Step #1: :27 min
Step #1: [INFO] Finished at: 2020-07-01T19:07:32Z
Step #1: [INFO] ------------------------------------------------------------------------
Finished Step #1
2020/07/01 19:07:43 Step Step #1 finished
2020/07/01 19:07:46 status changed to "PUSH"
PUSH
2020/07/01 19:07:46 status changed to "DONE"
DONE
```

**Review by nlumiere — APPROVED** [review]
sounds good

**Comment by leeannachen** [comment]
are we running this each time we make a pull request or is this automatic?

**Comment by aokeke** [comment]
> are we running this each time we make a pull request or is this automatic?

It will be automatic so each time you run merge it will deploy on its own.

**Comment by leeannachen** [comment]
> > are we running this each time we make a pull request or is this automatic?
> 
> It will be automatic so each time you run merge it will deploy on its own.

sweet 👍

**Review by leeannachen — APPROVED** [review]
lgtm

**Review by showermat — CHANGES_REQUESTED** [review]
Why are you running a package, then a package and deploy?  Delete the first step.

**Comment by aokeke** [comment]
> Why are you running a package, then a package and deploy? Delete the first step.

You're right. One, the deploy will build it on the way. and Two, the other rule will already build this.

**Review by showermat — APPROVED** [review]
Thanks for figuring this out!

**Pull request merged**
